### ISSUE TITLE
$e->message is a private member of Exception. Use getMessage()

### ISSUE THREAD

**Issue by JanThiel** [squarecandy/freemius-auto-activation#2]
https://github.com/squarecandy/freemius-auto-activation/blob/03c2b894cdf7113ec04dc49714a9fdb52fb01a51/class-freemius-license-auto-activator.php#L44

`$e->message` is a private member of `Exception`.
Should be ´$e->getMessage()`.

```php
$this->debug_notices( "Error: ".$e->getMessage() ); 
```

Best,

Jan

**Comment by petertwise** [comment]
@JanThiel - thank you! Fixed in 1.2.5
